"""empty message

Revision ID: 27d36afdc574
Revises: 201e59c006f1
Create Date: 2020-12-30 23:55:21.794803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27d36afdc574'
down_revision = '201e59c006f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('ami_id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('ami_id'),
    sa.UniqueConstraint('ami_id')
    )
    op.add_column('instances', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('instances', sa.Column('instance_id', sa.String(length=60), nullable=False))
    op.add_column('instances', sa.Column('password', sa.String(length=30), nullable=True))
    op.add_column('instances', sa.Column('state', sa.String(length=30), nullable=True))
    op.add_column('instances', sa.Column('username', sa.String(length=30), nullable=True))
    op.drop_index('ami_id', table_name='instances')
    op.create_unique_constraint(None, 'instances', ['instance_id'])
    op.drop_column('instances', 'name')
    op.drop_column('instances', 'description')
    op.drop_column('instances', 'ami_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances', sa.Column('ami_id', mysql.VARCHAR(length=60), nullable=False))
    op.add_column('instances', sa.Column('description', mysql.VARCHAR(length=512), nullable=True))
    op.add_column('instances', sa.Column('name', mysql.VARCHAR(length=60), nullable=True))
    op.drop_constraint(None, 'instances', type_='unique')
    op.create_index('ami_id', 'instances', ['ami_id'], unique=True)
    op.drop_column('instances', 'username')
    op.drop_column('instances', 'state')
    op.drop_column('instances', 'password')
    op.drop_column('instances', 'instance_id')
    op.drop_column('instances', 'created_date')
    op.drop_table('images')
    # ### end Alembic commands ###
