"""empty message

Revision ID: 773bdab2d6c2
Revises: 0d40dfccc5db
Create Date: 2020-12-30 00:15:46.643135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '773bdab2d6c2'
down_revision = '0d40dfccc5db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=60), nullable=True))
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', mysql.VARCHAR(length=60), nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
